apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  name: "app-service"
  namespace: "default"
  labels:
    app.kubernetes.io/name: "go-graphql_galaxy-service"
    app.kubernetes.io/component: "service"
spec:
  type: "LoadBalancer"
  selector:
    app.kubernetes.io/name: "go-graphql_galaxy-app"
    app.kubernetes.io/component: "app"
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: app-port
  loadBalancerIP: ""

