apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "app"
  namespace: "default"
  labels:
    app.kubernetes.io/name: "go-graphql_galaxy-app"
    app.kubernetes.io/component: "app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "go-graphql_galaxy-app"
      app.kubernetes.io/component: "app"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "go-graphql_galaxy-app"
        app.kubernetes.io/component: "app"
    spec:
      containers:
      - name: "go-graphql-galaxy-sha256-1"
        image: "gcr.io/devops-448416/go-graphql_galaxy-app:latest"
        ports:
          - containerPort: 8080
            name: app-port
        env:
          - name: APP_CONFIG_PATH
            value: "/config/cloud-galaxy.yaml"
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"