package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"go-graphql_galaxy/internal/gorm/services"
	"go-graphql_galaxy/internal/graphql/models"
	"go-graphql_galaxy/internal/transformers"
)

// Characters is the resolver for the characters field.
func (r *queryResolver) Characters(ctx context.Context) ([]*models.Character, error) {
	characterEntities, err := services.NewCharacterService(r.DB, GetPreloads(ctx)).Characters()
	if err != nil {
		return nil, err //! check business error
	}
	return transformers.TransformCharacterEntitiesToModels(characterEntities), nil
}

// Character is the resolver for the character field.
func (r *queryResolver) Character(ctx context.Context, id uint) (*models.Character, error) {
	characterEntity, err := services.NewCharacterService(r.DB, GetPreloads(ctx)).Character(id)
	if err != nil {
		return nil, err //! check business error
	}
	return transformers.TransformCharacterEntityToModel(characterEntity), nil
}
