ARG CORE_IMAGE=go-graphql_galaxy-core
FROM ${CORE_IMAGE} as base

COPY . .

# RUN go test ./...

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/app ./cmd/server/main.go

RUN apk add --no-cache bash
