networks:
  go-graphql_galaxy-db-only:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 5s  
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - go-graphql_galaxy-db-only
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data 
volumes:
  pgdata: