// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character struct {
	ID              uint       `json:"id"`
	Name            string     `json:"name"`
	Gender          *string    `json:"gender,omitempty"`
	Ability         string     `json:"ability"`
	MinimalDistance float64    `json:"minimal_distance"`
	Weight          *float64   `json:"weight,omitempty"`
	Born            string     `json:"born"`
	InSpaceSince    *string    `json:"in_space_since,omitempty"`
	BeerConsumption int32      `json:"beer_consumption"`
	KnowsTheAnswer  bool       `json:"knows_the_answer"`
	Nemeses         []*Nemesis `json:"nemeses"`
}

type Nemesis struct {
	ID        uint       `json:"id"`
	IsAlive   bool       `json:"is_alive"`
	Years     *int32     `json:"years,omitempty"`
	Character *Character `json:"character"`
	Secrets   []*Secret  `json:"secrets"`
}

type Query struct {
}

type Secret struct {
	ID         uint     `json:"id"`
	SecretCode int64    `json:"secret_code"`
	Nemesis    *Nemesis `json:"nemesis"`
}
