env: local
server:
  host: 0.0.0.0
  port: 8080
  use_playground: true
  use_introspection: true
  gql_complexity_limit: 100
  gql_depth_limit: 10

database:
  user: arthur
  password: xvQqwww2Kczb7cuJ2dvfPy15abC
  host: dontpanic.k42.app
  port: 5432
  db_name: galaxy
  sslmode: require
  timezone: UTC
